version: '3.8'
services:
  pgvector:
    container_name: pgvector_container
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: cv-store
      POSTGRES_PASSWORD: ayman
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
